apiVersion: v1
kind: Service
metadata:
  name: k8s-service
spec:
  clusterIP: None
  selector:
    app: k8s-pod
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k8s-statefulset
spec:
  serviceName: k8s-service
  replicas: 2
  selector:
    matchLabels:
      app: k8s-pod
  template:
    metadata:
      labels:
        app: k8s-pod
    spec:
      containers:
        - image: 130620/k8s-statefulsets
          name: k8s-pod-container
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: k8s-persistent-volume-claim
              mountPath: /var/data
  volumeClaimTemplates:
    - metadata:
        name: k8s-persistent-volume-claim
      spec:
        resources:
          requests:
            storage: 1Mi
        accessModes:
          - ReadWriteOnce
