apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-replication-controllers
spec:
  replicas: 2
  selector:
    app: k8s-pod
  template: # Config of Pods
    metadata:
      labels:
        app: k8s-pod
    spec:
      containers:
        - image: 130620/k8s-pod
          name: k8s-pod-container
          ports:
            - containerPort: 3000
              protocol: TCP
