apiVersion: v1
kind: Pod
metadata:
  name: k8s-volume-hostpath
spec:
  containers:
    - image: nginx:alpine
      name: k8s-pod-container
      volumeMounts:
        # - name: html
        #   mountPath: /usr/share/nginx/html
        #   readOnly: true
        - name: logs
          mountPath: /var/log/nginx
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: logs
      hostPath:
        path: /var/log
        type: DirectoryOrCreate
