apiVersion: v1
kind: Pod
metadata:
  name: k8s-pod-test
  labels:
    environment: test
  # namespace: local-test
spec:
  containers:
    - image: 130620/k8s-pod
      name: k8s-pod-test
      ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-pod-production
  labels:
    environment: production
  # namespace: local-production
spec:
  containers:
    - image: 130620/k8s-pod
      name: k8s-pod-production
      ports:
        - containerPort: 3000
          protocol: TCP
