apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-persistent-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: '/mnt/data'
