apiVersion: v1
kind: Pod
metadata:
  name: k8s-volume-mongo
spec:
  containers:
    - image: mongo
      name: k8s-pod-container
      volumeMounts:
        - name: k8s-volume-storage
          mountPath: /data/db
      ports:
        - containerPort: 27017
          protocol: TCP
  volumes:
    - name: k8s-volume-storage
      persistentVolumeClaim:
        claimName: k8s-persistent-volume-claim
