apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
