apiVersion: v1
kind: Pod
metadata:
  name: k8s-config-map-example
spec:
  containers:
    - image: 130620/k8s-config-map
      name: k8s-pod-container
      ports:
        - containerPort: 3000
      envFrom:
        - configMapRef:
            name: k8s-config-map
